language: node_js 

os:
  - linux

node_js:
  - "stable"

cache:
  directories:
  - node_modules

before_install:
  - cd server/dbInterface

install:
  - npm install
  - cd ../tests
  - npm ci

script:
  - npm test
